### ISSUE TITLE
Error when parsing true as environment variable

### ISSUE THREAD

**Issue by eisemakr** [eshepelyuk/apicurio-registry-helm#16] opened 2023-07-18 12:10 UTC
When installing as described in the readme I experience an error when I try to set an extra Environment variable. 

helm upgrade -i --wait -n apicurio apicurio-registry oci://ghcr.io/eshepelyuk/helm/apicurio-registry --version 2.2.0 --set registry.extraEnv[0].name="AUTH_ENABLED" --set registry.extraEnv[0].value="true" 

Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
apicurio-registry:
- registry.extraEnv.0.value: Invalid type. Expected: string, given: boolean

Do I do anything wrong or is it a bug that true can't be parsed as string?

**Comment by eshepelyuk** [comment] 2023-07-18 12:33
Hello @eisemakr 

I assume this issue gonna help

https://github.com/helm/helm/issues/2848

**Comment by eisemakr** [comment] 2023-07-18 12:49
Hey @eshepelyuk 

thx for your help. --set-string did the work.

**Comment by eshepelyuk** [comment] 2023-07-18 12:51
> Hey @eshepelyuk 
> 
> thx for your help. --set-string did the work. 

So why the issue is still open ?

**Comment by eshepelyuk** [comment] 2023-07-18 17:08
Hello @eisemakr 

Why don't you close the issue ? Do you have anything to add to it ?

**Closed** 2023-07-19 07:13 UTC
